### ISSUE TITLE
Add the aspect ratio component as per react components

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon-components-vue#1059]
See https://react.carbondesignsystem.com/?path=/story/aspectratio--aspect-ratio

**Comment by floriankapaun** [comment]
Hey @lee-chase, I just came across that the aspect ratio module is not available yet. Can you tell me what the reason is? 

I saw that the module is already built: https://github.com/carbon-design-system/carbon-components-vue/tree/main/packages/core/src/components/cv-aspect-ratio
And there is a storyboard for it as well: https://vue.carbondesignsystem.com/?path=/story/components-cvaspectratio--default

If anything else needs to be done, I'm happy to create a pull request.

**Comment by lee-chase** [comment]
I have not completed the other component updates for 10.30 Carbon, due to other demands on my time. A canary release could be made without the other component updates if it helps.

**Comment by floriankapaun** [comment]
Thanks for your fast reply @lee-chase. No need to publish an extra canary release. I just added the component manually to my Vue project which is fine for now. Do you have a rough time frame when the 10.30 update will be finished? 😬

**Comment by lee-chase** [comment]
Tricky to say, hoping to find some time during next week.

**Comment by davidnixon** [comment]
Implemented in Vue 3 src/components/CvAspectRatio
