### ISSUE TITLE
[cv-search] magnifying glass is displayed outside the input field

### ISSUE THREAD

**Issue by tbs-heiss** [carbon-design-system/carbon-components-vue#1229]
## Summary
Hello everyone, I have a problem with the cv-search. It's not possible for me to imagine the component in such a way that the magnifying glass is displayed inside the field. 

## Relevant information

For me it looks like this: 
![image](https://user-images.githubusercontent.com/84387353/127109856-82fa3ec5-7e4b-4743-aca7-644e8fd74874.png)

In the library, however, it looks like this:
![image](https://user-images.githubusercontent.com/84387353/127109885-6b1addfc-adf4-40bc-8fe8-9268eb21edbe.png)

My code looks like this:

`  <cv-form class="form" @submit.prevent="actionSubmit">`
 `     <cv-search`
  `      class="search"`
   `     label= "Search label"`
    `    placeholder="Search Placeholder"`
     `   clearArialabel= "Custom search aria label"`
      `>`
      `</cv-search>`
      `<cv-button class="button">Suchen</cv-button>`
  `</cv-form>`

I have tried it in different variations, as well as outside the form. The problem remains.
I am happy to receive tips and suggestions for solutions.

**Comment by trickstival** [comment]
I tried it out [in this sandbox](https://codesandbox.io/s/carbon-components-vue-forked-2e4n5?file=/src/TestComponent.vue)
with your code and it looks fine.

It's hard to say what's going on without more info, but you might be overriding the library's css.

**Comment by ChoroDev** [comment]
The main issue here is that new versions of carbon-components have class 'bx--search-magnifier-icon' instead of 'bx--search-magnifier'. And when you try to use carbon-components-vue with them, this happens
Proposed solutions for now: 
1. You can downgrade your 'carbon-components' package to 10.30.0 and get rid of that issue for now
![image](https://user-images.githubusercontent.com/29352750/129338118-aeac5cf6-bb4f-4656-9ba8-c126a15bbfa0.png)
2. You can change the class name manually in provided path:
node_modules/@carbon/vue/src/components/cv-search/cv-search.vue
![image](https://user-images.githubusercontent.com/29352750/129338385-05032971-d440-4232-8998-f671b1d73d2a.png)
