### ISSUE TITLE
Custom cv-data-table  header 

### ISSUE THREAD

**Issue by peakrock** [carbon-design-system/carbon-components-vue#758]
I want custom  cv-data-table  header ,  could you  add `slot ` for v-data-table header ?

**Comment by lee-chase** [comment]
@peakrock based on the images am I right in thinking you want to be able to change the contents of the table headers cv-data-table-heading. Perhaps the label with other content?

The headings outside of columns added for expansion, batch actions and overflow menu could adopt the same pattern as data. However, sorting is currently built into each cv-data-table-heading so that might be tricky to figure out.

Feel free to submit a PR with your thoughts.

**Comment by lee-chase** [comment]
@peakrock If this were possible it looks like it would be an alternative to sorting. Is this the case?

If so I think could be a candidate for core carbon @joshblack, but I'm finding it hard to justify adding complexity to the CvDataTable without it being so. 

Will leave open in case of inspiration.

**Comment by lee-chase** [comment]
Been thinking about this with the submission of #890 

It may be possible to do this by 
1. Adding a slot to allow the user to define the headers
2. Promoting the header item to a full component (removing _ from name).
3. Adding slots to the header item to allow the user to put dynamic content into the label.
4. Having the header item register with the header to manage sorting where used.

Might even be nice if a tooltip could be provided without the need to add a full tooltip.

**Comment by lee-chase** [comment]
@peakrock Does the canary update suit your needs?

**Comment by lee-chase** [comment]
Added to previous release
